import { relations } from "drizzle-orm";
import { pgTable, text, timestamp, boolean, index } from "drizzle-orm/pg-core";

// Generated by `npx @better-auth/cli generate --config src/platform/auth.ts --output
// src/platform/auth-tables.ts` (see data-model.md: "Better Auth manages app_user, session,
// account, and verification"; `user` is renamed to `app_user` because `user` is reserved in
// PostgreSQL). The CLI names its exports snake_case; they're renamed to camelCase here to match
// this codebase's convention (conventions.md) — re-apply that rename if this file is regenerated.
export const appUser = pgTable("app_user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
});

export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at").notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => appUser.id, { onDelete: "cascade" }),
  },
  (table) => [index("session_userId_idx").on(table.userId)],
);

export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => appUser.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at"),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
    scope: text("scope"),
    password: text("password"), // unused — no password sign-in exists in this app (accounts-roles.md)
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("account_userId_idx").on(table.userId)],
);

export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)],
);

// The @better-auth/sso plugin's own table (register-city-sso-provider.ts writes to it via
// auth.api.registerSSOProvider — never directly).
export const ssoProvider = pgTable("sso_provider", {
  id: text("id").primaryKey(),
  issuer: text("issuer").notNull(),
  oidcConfig: text("oidc_config"),
  samlConfig: text("saml_config"),
  userId: text("user_id").references(() => appUser.id, { onDelete: "cascade" }),
  providerId: text("provider_id").notNull().unique(),
  organizationId: text("organization_id"),
  domain: text("domain").notNull(),
});

export const appUserRelations = relations(appUser, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
  ssoProviders: many(ssoProvider),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  appUser: one(appUser, { fields: [session.userId], references: [appUser.id] }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  appUser: one(appUser, { fields: [account.userId], references: [appUser.id] }),
}));

export const ssoProviderRelations = relations(ssoProvider, ({ one }) => ({
  appUser: one(appUser, { fields: [ssoProvider.userId], references: [appUser.id] }),
}));

// Better Auth's Drizzle adapter resolves each model to a table by looking up this whole module
// (passed as `schema` in auth.ts) using the *model name* as the object key — and `user`'s model
// name is configured as "app_user" (see the comment at the top of this file), not "appUser". This
// alias is what makes that lookup succeed; every application import still uses `appUser`.
export { appUser as app_user };
